### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by nassimabedi** [mushorg/glutton#101]
I have this error many times.

> 2017/11/28 18:31:16 DEBUG [freki   ] new TCP connection x.x.x.x:x->22
> 2017/11/28 18:31:16 DEBUG [contable] registering x.x.x.x:x->22
> 2017/11/28 18:31:16 ERROR [user.tcp] panic: runtime error: invalid memory address or nil pointer dereference
> 2017/11/28 18:31:16 ERROR [user.tcp] stacktrace:
> goroutine 21245 [running]:
> runtime/debug.Stack(0xc42000e3f0, 0xa89c2a, 0x15)
>         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
> github.com/mushorg/glutton/vendor/github.com/kung-foo/freki.(*UserConnServer).Start.func1.1(0xfc1960, 0xc42000e5f8)
>         /x/x/x/x/src/github.com/mushorg/glutton/vendor/github.com/kung-foo/freki/userconnhandler_tcp.go:66 +0xda
> panic(0x9c4ee0, 0xfa6f90)
>         /usr/local/go/src/runtime/panic.go:489 +0x2cf
> github.com/mushorg/glutton.(*sshProxy).handle(0x0, 0xfbd5c0, 0xc422b9bc80, 0xfc1960, 0xc42000e5f8, 0x0, 0x0)
>         /x/x/x/x/src/github.com/mushorg/glutton/proxy_ssh.go:131 +0xb2
> github.com/mushorg/glutton.(*Glutton).mapProtocolHandlers.func9(0xfbd5c0, 0xc422b9bc80, 0xfc1960, 0xc42000e5f8, 0xc42141e808, 0x0)
>         /x/x/x/x/src/github.com/mushorg/glutton/protocols.go:51 +0x56
> github.com/mushorg/glutton.(*Glutton).registerHandlers.func1(0xfc1960, 0xc42000e5f8, 0xc422b9b950, 0xc42000e5f8, 0x0)
>         /x/x/x/x/src/github.com/mushorg/glutton/glutton.go:214 +0x3d3
> github.com/mushorg/glutton/vendor/github.com/kung-foo/freki.(*UserConnServer).Start.func1(0xfc1960, 0xc42000e5f8, 0xc421430300, 0xc422b9b950, 0xc4214302e0)
>         /x/x/x/x/src/github.com/mushorg/glutton/vendor/github.com/kung-foo/freki/userconnhandler_tcp.go:70 +0x7c
> created by github.com/mushorg/glutton/vendor/github.com/kung-foo/freki.(*UserConnServer).Start
>         /x/x/x/x/src/github.com/mushorg/glutton/vendor/github.com/kung-foo/freki/userconnhandler_tcp.go:74 +0x32c

**Comment by glaslos** [comment]
Any idea what's causing this?

**Comment by nassimabedi** [comment]
I used Vmware ( 1G RAM , 1 core CPU , 1.8 go version) when I had this error.
but now I use host (3 G RAM , 2 core CPU , 1.9 go version) and there is no error at all during few days.(almost two weeks)
