### ISSUE TITLE
[glutton ] open rules/rules.yaml: no such file or directory

### ISSUE THREAD

**Issue by Jahanzaib-int** [mushorg/glutton#105]
I am trying to compile the code. It gives no error in build command but when I run the server file it gives the following error
[glutton ] open rules/rules.yaml: no such file or directory

**Comment by nassimabedi** [comment]
The "rules" folder must be in a directory that you try to run.

**Comment by Jahanzaib-int** [comment]
Ohh Thank you I have managed to resolve issue...
