### ISSUE TITLE
Building error: smb.go:245: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/glutton#107]
When building with Alpine (edge) and go 1.10.x I am getting the following error

```
# github.com/mushorg/glutton/protocols/smb
go/src/github.com/mushorg/glutton/protocols/smb/smb.go:245: multiple-value uuid.NewV4() in single-value context
```

I googled the error and an [API change](https://github.com/satori/go.uuid/issues/66) seems to be the cause.

**Comment by Vikash082** [comment]
I see following lines in generator.go.

func NewV4() (UUID, error) {
	return global.NewV4()
}

The function is changed and it breaking the earlier references.

**Comment by glaslos** [comment]
Did you use `dep ensure` for the dependencies?

**Comment by t3chn0m4g3** [comment]
Yes.

**Comment by t3chn0m4g3** [comment]
@glaslos Thank you, 5f845479f9786024386ed31affa839e7c0da0b27 fixed it.

**Comment by glaslos** [comment]
Strange, that wasn't really related...

**Comment by t3chn0m4g3** [comment]
@glaslos LOL, I just ran the same Dockerfile and the error messages did not appear again :stuck_out_tongue_winking_eye:
