### ISSUE TITLE
Error: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by Bartlett-Will** [mushorg/glutton#113]
I am running go version 1.10.3 linux/amd64 and am getting the following error when I try to download glutton from git. 

# github.com/mushorg/glutton/protocols/smb
src/github.com/mushorg/glutton/protocols/smb/smb.go:245:36: multiple-value uuid.NewV4() in single-value context

It seems like everything worked out, but after getting dep and navigating to the appropriate directory, i get, "No command 'dep' found". 

I have read that this is an API breaking change to uuid.NewV4()?

**Comment by glaslos** [comment]
You have to install dep either using go: `go get -u github.com/golang/dep/cmd/dep` and make sure your bin directory is in your PATH or install  it with a packet manager. Then with dep you should get the required dependencies. Alternatively you can manually check out the 1.2 version of uuid.

**Comment by Bartlett-Will** [comment]
Okay, my PATH must be wrong, thank you.
