### ISSUE TITLE
Proxy and logging feature for Telnet 

### ISSUE THREAD

**Issue by cstayyab** [mushorg/glutton#114]
I want to add a telnet proxy feature just like SSH Proxy so that it can communicate with a remote Telnet machine or honeypot and return connection to the attacker. Can you give a starting point?

**Comment by glaslos** [comment]
`proxy_tcp` should work for you

**Comment by cstayyab** [comment]
But I also want to log the connection... But proxy_tcp is not logging....

**Comment by glaslos** [comment]
Should be fairly straight forward to add. Just have a look at the other
protocol handlers.

**Comment by cstayyab** [comment]
Thanks for the tip. 
I have successfully coded that and I have tested it. It is working perfectly with logging features. **Should I initiate a pull request so you can add it to the repository?**

**Comment by glaslos** [comment]
Sure, send it in!

**Comment by cstayyab** [comment]
Please accept the pull request [#115](https://github.com/mushorg/glutton/pull/115)

Thanks
