### ISSUE TITLE
Set --var-dir on startup 

### ISSUE THREAD

**Issue by Jc2k** [mushorg/glutton#134]
Reading the code, there is a setting for `var-dir`. But it looks like its only set from the config file after it is already read to do `g.makeID()`? I think right now it exists mostly for glutton_test.go, but it would be nice if there was a way to set it from conf.yml or cmd line etc.

**Comment by glaslos** [comment]
You can add it here as a flag: https://github.com/mushorg/glutton/blob/master/app/server.go#L56 so we don't need to set it here: https://github.com/mushorg/glutton/blob/master/glutton.go#L53
