### ISSUE TITLE
Close connections after a set timeout

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#138]
We want to close connections after a set timeout. The timer should be reset whenever we receive a new message on the connection. The timeout should be configurable via a flag and should be two minutes by default. Handlers should also exit when the connection closes.

**Comment by Hyperion101010** [comment]
Looks like changes will on spf13/pflag, isn't it @glaslos .

**Comment by nassimabedi** [comment]
I think about goroutine with context (canceled with context). Is it ok? @glaslos

**Comment by glaslos** [comment]
We already have a bit of code for this. but it's not really working. You can see when you shut down Glutton that we try to close a lot of connections which are actually not active anymore. If you run Glutton for a long time this can take a forever. Sometimes this causes the iptables rules not to reset rendering your machine unusable until reboot.
