### ISSUE TITLE
ARM64 support broken for latest master

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/glutton#146]
For the latest master ARM64 support is broken due to ...
```
# github.com/jart/gosip/dsp
../pkg/mod/github.com/jart/gosip@v0.0.0-20200629215808-4e7924e19438/dsp/dsp.go:22:6: missing function body
../pkg/mod/github.com/jart/gosip@v0.0.0-20200629215808-4e7924e19438/dsp/dsp.go:28:6: missing function body
../pkg/mod/github.com/jart/gosip@v0.0.0-20200629215808-4e7924e19438/dsp/dsp.go:31:6: missing function body
```
... an issue has been opened [here](https://github.com/jart/gosip/issues/23), without a solution in sight.

Is there maybe an alternative in using another module with multiarch support?

**Comment by t3chn0m4g3** [comment]
The modules in question were introduced with 22dd73a110d457309fd66527ede46e402c3ff226.

**Comment by glaslos** [comment]
This has been resolved in the latest master

**Comment by t3chn0m4g3** [comment]
Thank you for tracking 🤩
