### ISSUE TITLE
Get the original destination port

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#2]
Investigate if we get enough information from `/proc/net/nf_conntrack` or `/proc/net/ip_conntrack`

**Comment by MohammadBilalArif** [comment]
```/proc/net/nf_conntrack``` and ```/proc/net/ip_conntrack``` has been deprecated. Now in latest kernel ```conntrack application``` is  available as interface to nf_conntrack kernel module. I have installed conntrack. So next we will use conntrack?

**Comment by glaslos** [comment]
Correct. Go for it.

**Comment by glaslos** [comment]
I recommend using a go channel for communication between the conntrack reader and the Glutton service. If you want non-blocking channels, have a look at https://github.com/hectane/go-nonblockingchan with an explanation here: https://blog.quickmediasolutions.com/2015/09/13/non-blocking-channels-in-go.html Although it might be fine if the conntrack reader waits with pushing new data to the channel until we consumed from the channel (or introduce a buffer).
