### ISSUE TITLE
Default handler

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#30]
I'd like to have a handler that I can assign to ports:
```yaml
ports:
  21:
    default
```
Default handler should accept the connection and read the package payload. This might trigger additional packages.

**Comment by MohammadBilalArif** [comment]
Right, Well you can elaborate about additional packages?

**Comment by glaslos** [comment]
Very simple: If we accept a package (establish a connection), the adversary might send additional ones.

**Comment by glaslos** [comment]
done with https://github.com/mushorg/glutton/pull/32/commits/8e808a59bc6451e113667849fddc794ee00fe244
