### ISSUE TITLE
Fix the readme

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#40]
Readme needs an update after we changed the core to Freki.

**Comment by kalyan-kumar** [comment]
I would like to contribute. It would be great if you could you direct me how to go about understanding the project to start off.

**Comment by glaslos** [comment]
Are you trying to solve this issue? If so, why not start with attempting to run Glutton?

**Comment by kalyan-kumar** [comment]
Yeah, I am trying to solve the issue. But as the issue says, I am unable to get glutton running by following the README. I am currently going to Freki to figure out what has to be done. Could you point me to some resources so that I could get a headstart?

**Comment by glaslos** [comment]
Are you familiar with Golang? Try building the `main` package in the `app` directory. You will encounter dependency issues. You want to use `glide` to install the dependencies.

**Comment by kalyan-kumar** [comment]
I set it up. But while running the app executable, I get the following error 
`FATA[0000] eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device`.

This is because, in Ubuntu 16.04 (that I am using), the network interfaces are renamed to follow a different convention. Mine is named `enp3s0f1`. How should I be proceeding now?

**Comment by glaslos** [comment]
Try `./glutton -h`

**Comment by kalyan-kumar** [comment]
But the executable produced is named app, and it doesn't support -h argument.

**Comment by glaslos** [comment]
How do you build the executable?

**Comment by kalyan-kumar** [comment]
`go install` inside app directory. And `go install` inside project's root. Only one executable called `app` was produced in bin.

**Comment by glaslos** [comment]
try `go run app/server.go -h`

**Comment by kalyan-kumar** [comment]
`-h` option isn't supported. I get the following output, which is similar to what is obtained when app executable is run.

`INFO[0000] [glutton ] Loading rules from: /etc/glutton/rules.yaml`
`INFO[0000] [glutton ] Rules: [Rule: tcp dst port 5001 Rule: tcp dst port 23 or port 2323 or port 23231 Rule: tcp]`
`FATA[0000] wlp2s0: You don't have permission to capture on that device (socket: Operation not permitted)`
`exit status 1`

**Comment by glaslos** [comment]
```
go run app/server.go -h

  _____ _       _   _
 / ____| |     | | | |
| |  __| |_   _| |_| |_ ___  _ __
| | |_ | | | | | __| __/ _ \| '_ \
| |__| | | |_| | |_| || (_) | | | |
 \_____|_|\__,_|\__|\__\___/|_| |_|

	
Usage of /tmp/go-build161818327/command-line-arguments/_obj/exe/server:
  -debug
    	Set to enable debug log
  -interface string
    	Interface to work with (default "eth0")
  -log string
    	Log path (default "/dev/null")
  -rules string
    	Rules path (default "/etc/glutton/rules.yaml")
exit status 2
```

**Comment by kalyan-kumar** [comment]
Yeah I was getting this with `-h` option. I thought it meant `-h` wasn't supported. My mistake. So does this mean setup is complete?

**Comment by glaslos** [comment]
Read :)

**Comment by glaslos** [comment]
Done with #41
