### ISSUE TITLE
No ports.yml found

### ISSUE THREAD

**Issue by ameygat** [mushorg/glutton#43]
There is no ports.yml source files.

cp $GOPATH/src/github.com/mushorg/glutton/config/ports.yml /etc/glutton

```
root@debian8template:/# cp $GOPATH/src/github.com/mushorg/glutton/config/ports.yml /etc/glutton
cp: cannot stat ‘/opt/go/src/github.com/mushorg/glutton/config/ports.yml’: No such file or directory

```

**Comment by glaslos** [comment]
The current readme is outdated, see #41 use the rules.yaml file in the rules/ directory.
