### ISSUE TITLE
Issue with freki

### ISSUE THREAD

**Issue by ameygat** [mushorg/glutton#44]
I tried to run the server.go from /app/server.go but getting error in freki package.

I had installed freki using command:
 go get github.com/kung-foo/freki

Also tried:
 go install golang.org/x/net/context

But same error while running
```
root@debian8template:/opt/go/src/github.com# go run /opt/go/src/github.com/mushorg/glutton/app/server.go 
kung-foo/freki/freki.go:4:2: cannot find package "context" in any of:
	/usr/lib/go/src/pkg/context (from $GOROOT)
	/opt/go/src/context (from $GOPATH)
```

Am I doing something wrong here ?

**Comment by MohammadBilalArif** [comment]
Make sure you are running Go version 1.7+

**Comment by MohammadBilalArif** [comment]
``Context`` became part of the standard library in go 1.7. I guess your go version is below that number.
