### ISSUE TITLE
Invisible Glutton crash/panic

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#59]
I'm running Glutton directly on my server. Every 1-2 days the server becomes unreachable. I assume Glutton crashed and didn't clean up the iptables rules, locking me out from the machine. I have to reboot the box in order to access it again. I tail stderr to a file to see if there is any output, so far without luck. I assume we never execute https://github.com/kung-foo/freki/blob/master/freki.go#L245 on a panic.

**Comment by t3chn0m4g3** [comment]
I have the same behaviour when using glutton with `network_mode: "host"`. Starting the container works fine and everything works as expected. Gracefully stopping (`docker-compose down -v`) results in the machine being unreachable.

Thoughts?

**Comment by t3chn0m4g3** [comment]
I increased the graceful shutdown period to 120 seconds while monitoring the debug output, which basically prints the following lines for 120 seconds:
```
{"level":"info","ts":1523658022.4271533,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658032.4269712,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658042.4279432,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658052.427788,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658062.4275613,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658072.427133,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658082.427789,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658092.427497,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658102.4270444,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
{"level":"info","ts":1523658112.4276683,"caller":"glutton/system.go:34","msg":"[system  ] running Go routines: 19 and open files: 9","sensorID":"2db13527-0def-4544-8727-4d02dee24a96"}
```
Once the container is stopped any open (and by configuration set to pass through) SSH connection will be cut off, however restarting the container also results in the SSH connection being revived.

**Comment by t3chn0m4g3** [comment]
Docker sends by default a `SIGHUP` to end processes, or does glutton need a different signal to trigger a clean up before exiting?

**Comment by glaslos** [comment]
Ah, that might be something, I am expecting a [SIGINT](https://github.com/mushorg/glutton/blob/master/app/server.go#L34)

**Comment by glaslos** [comment]
I think it makes most sense to handle SIGHUP in Glutton as well. Let me add that line..

**Comment by glaslos** [comment]
I added SIGHUP to the interrupt handler, check if that works now.

**Comment by glaslos** [comment]
No sweat, thanks for reporting!

**Comment by t3chn0m4g3** [comment]
@glaslos For the record, the tests this morning were showing SIGHUPs for whatever reason, but I got this wrong. Checked the FAQs and docker sends by default a [SIGTERM](https://docs.docker.com/compose/faq/).

**Comment by t3chn0m4g3** [comment]
If anyone else needs the docker shell form instead of the exec form `exec` will do the trick by replacing the shell process resulting in SIGTERM reaching glutton:
```
CMD exec bin/server -i ens33 -l /var/log/glutton/glutton.log -d true
```
