### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#65]
Glutton eventually fails with:

`[user.tcp] accept tcp [::]:5000: accept4: too many open files`

**Comment by furusiyya** [comment]
It is because of crashing freki. I have opened an [issue](https://github.com/kung-foo/freki/issues/21) there.

**Comment by gento** [comment]
Yeah this issue hit me for the past few weeks. Glutton generated 15 GB log for me with the "too many open files" message, and kill my sensor. In fact the real log is just 50mb++.

**Comment by furusiyya** [comment]
@gento `15 GB` logs?  real logs? I could not understand. You can elaborate little bit?

**Comment by gento** [comment]
my glutton generated a 15GB log file past few weeks. It mainly contained the lines:

`[user.tcp] accept tcp [::]:5000: accept4: too many open files`

After I excluded the lines within the 15GB log file, the remaining lines consumed 50MB only.

**Comment by gento** [comment]
For example:

```
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files 
ERRO[478626] [user.tcp] accept tcp [::]:5000: accept4: too many open files
```

**Comment by furusiyya** [comment]
ok .. got it. Thanks :)

**Comment by glaslos** [comment]
Duplicate of #72
