### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#72]
I'm still having this issues:
`[user.tcp] accept tcp [::]:5000: accept4: too many open files`

**Comment by furusiyya** [comment]
`[user.tcp]` indicates the existence of error on freki side, btw I will try to reveal this bug.

**Comment by glaslos** [comment]
Checking the number of running go routines might give you a hint?

**Comment by glaslos** [comment]
@furusiyya see https://github.com/mushorg/glutton/commit/cda0aca5034a2e1812ee4c012fe90c32c9f36919

**Comment by glaslos** [comment]
`Running Go routines: 440 and open files: 437`
There are definitely routines still running that shouldn't

**Comment by glaslos** [comment]
Closed with 82c1e54
