### ISSUE TITLE
Add cli for management

### ISSUE THREAD

**Issue by furusiyya** [mushorg/glutton#75]
[Cli](https://github.com/urfave/cli) provides very easy way to register, order and categorize commands, optional flags required to run a command line application. Source of input can also be a json or toml. We can register init and exit code for our application. It provides context that travels to all handler functions of application, so flags can be accessed and set at any level of application with the help of context. Context can be used to track and shutdown goroutines.

**Comment by glaslos** [comment]
Could you add more details what sort of management you envision?

**Comment by furusiyya** [comment]
@glaslos  updated :)

**Comment by glaslos** [comment]
This might be relevant: https://medium.com/@matryer/bd006a8ad6ff

**Comment by furusiyya** [comment]
exactly! this is the only we can close all connections before calling shutdown.

**Comment by glaslos** [comment]
Fixed in b9cf8c2
