### ISSUE TITLE
Add Docker build check to Travis

### ISSUE THREAD

**Issue by dpisano** [mushorg/glutton#78]
Currently the Travis tests do not check if the docker image builds successfully. There are two ways that I can see this going. The first is to build the docker image and then run the unit test on it too and the other is to just build the docker image.

**Comment by dpisano** [comment]
So looking at how the unit test works we will not be able to run it in the docker container. The unit test has a number of dependencies on packages that are removed during the docker build process. I can make the needed changes to `.travis.yml` to make sure the docker image builds and that it runs.

**Comment by dpisano** [comment]
I have this working on my fork. Would you like me to make a PR? As a note `go test` does not work on my fork.

**Comment by glaslos** [comment]
Seems like the sub packages are not installed or your Gopath is not set correctly.

**Comment by dpisano** [comment]
As per a previous discussion the errors from `go test` are from travis.

**Comment by dpisano** [comment]
Do you want to to just submit a PR for for what I have for this?

**Comment by glaslos** [comment]
Absolutely!

**Comment by dpisano** [comment]
I have submit PR #92 for this. It looks like there are some problems on the docker side right now.

**Comment by dpisano** [comment]
Merged with PR #96.
